### ISSUE TITLE
The AWS profile is not taken into account when deploying

### ISSUE THREAD

**Issue by mnapoli** [serverless/compose#120]
I have 3 AWS profiles setup on my system. Howver, I am having issues with using any of these profiles except the default one. None of the options above work for me.
- explicity stating the profile name under `provider.profile` is not working
- using the per stage profile setup is also not working
-  setting the `AWS_PROFILE` environment variable
Each time, it always uses the default profile, regardless of what I put in...

_Originally posted by @mkarsene in https://github.com/serverless/compose/issues/113#issuecomment-1126948205_

**Comment by mnapoli** [comment]
@mkarsene I'm surprised that `provider.profile` doesn't work. Could you clarify:

- is it working when deploying without Compose, via `serverless deploy` in the same directory as `serverless.yml`?
- is it working when deploying _with_ Compose, via `serverless deploy` in the same directory as `serverless-compose.yml`?

I'm trying to identify if the issue is related to Compose or not.

Have you managed to make the profiles work before using Compose?

**Comment by mkarsene** [comment]
@mnapoli I am using serverless.ts but I assume this has no effect on any of this? 
- Doesn't work in the first case. Both with and without compose. 
- The second case I've been unable to test as I can't figure out how to setup the `path: "same-directory-as-serverless-ts"`. I thought that if I don't include the path, it would assume the `serverless.ts` is within the same directoy as the `serverless-compose.ts`, But it threw a no path error. Tried `path: "" `,`path: "./"` and `path: "."` Still no joy....
- I was able to make it work using the `set AWS_PROFILE=my-profile-name` though. The first time didn't work as I'd used `export AWS_PROFILE` instead of `set AWS_PROFILE` on a windows machine. My bad

**Comment by mnapoli** [comment]
Got it. `serverless.ts` instead of `serverless.yml` should have no impact here.

Could you post the full `serverless.ts` file (with sensitive parts removed)? I want to see if there's anything else that might override the AWS profile configuration.

---

Regarding `serverless-compose.ts`, you cannot set `'.'` or `''` as a path: the service has to be in a different directory. This is because else `serverless deploy` cannot decide if it should run Compose or Serverless Framework (because both config files are in the same directory).

This is something we want to improve/solve in the future.

**Comment by mkarsene** [comment]
I believe my issue was that I'd set the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env params in windows. These somehow took precedence over the `provider.profile` variable in any `serverless.ts`. deleting those from the windows env solved it...

**Comment by pgrzesik** [comment]
Hey @mkarsene - that's definitely the case - the environment variables always take precedence over the `profile` setting

**Comment by mnapoli** [comment]
👍 

Let's close this issue then as it seems the problem was identified.

**Comment by mkarsene** [comment]
I think we can close this issue then...thanks @mnapoli

**Comment by muddahany** [comment]
I am having a similar issue to that one, where I am having a Makefile that basically loads up the AWS credential inside a profile. When using the same `Makefile` we use for other services to a newly monorepo service with `serverless-compose`, the following scenarios took place when running the CD on ubuntu
- Using aws-profile in the serverless cli params didn't work since it isn't yet supported by sls-compose.
- Setting the profile name on serverless.yml in the subpackages didn't load the profile but rather used the default one; even though when echoing using `@aws sts get-caller-identity --profile serverless` inside the `Makefile` , the correct credentials were loaded.
- Setting env var with AWS_PROFILE= also does not work and serverless assumes the default profile.
