### ISSUE TITLE
Simplify service outputs in info

### ISSUE THREAD

**Issue by mnapoli** [serverless/compose#15]
- Remove service outputs from deploy
- Rename `sls outputs` to `sls info`

**Comment by pgrzesik** [comment]
I'm not sure if we should continue the discussion in this or start other issue, but we were recently talking about the need to simplify the outputs from the `deploy` command and potentially from `info`. 

Currently, it just prints out all of the data gathered from `sls info` command that is stored as `outputs` in state file. In order to make it cleaner, I would suggest that we follow similar approach that we currently have in Framework, which hides some of the information if `--verbose` flag is not present. In case of the `compose`, we could stick to presenting the following without verbose:
- `region`
- `endpoint(s)`
- `function(s)`
- `apikey(s)`
- `layers`

and additionally with verbose
- Stack outputs

We can also move e.g. `apiKeys` and `layers` to stack outputs to keep things cleaner.

On state level, we would have to introduce metadata about the "type" of the value stored as `outputs` for each service and process it accordingly during `info` command.

What do you think @mnapoli ?

**Comment by mnapoli** [comment]
👍  let's go with this.
