### ISSUE TITLE
Handle first `serverless deploy` in non-interactive

### ISSUE THREAD

**Issue by mnapoli** [serverless/compose#87]
Since `serverless deploy` needs to install Compose, there can be scenarios where compose is not installed (e.g. in CI). In non-interactive mode (i.e. CI again) the CLI is just stuck:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/720328/163553827-4d1dc605-3ffd-4262-86cc-7b44207c0c0e.png">

We could imagine 2 solutions:

1. throw an error inviting the user to install Compose via NPM first
2. auto-install Compose (i.e. assume "Y" by default)

Since non-interactive will run in CI 90% of the time, I would go with option 2 because:

- if you set up Compose in CI, it's likely you already know what you are doing and want Compose
- you probably already installed Compose locally, you just forgot to run `npm install` at the root of the monorepo
- it's annoying to edit the CI to run `npm i` at the root _just for compose_ -> it should just work, we don't want to push the detail of the NPM install on users too much (to the point it's annoying)

I would consider the surprise factor very low since, again, you are explicitly running Compose so there's little chance you actually don't want to install it? WDYT @pgrzesik

**Comment by pgrzesik** [comment]
Great point raising that @mnapoli - I missed that. 

I'm not sure we should install it automatically for users and would prefer to throw an explicit error - if they're adopting compose for the first time, they will be aware that it needs to be installed separately and I don't think it will be a big problem for them to install `compose`. They most likely will have it in local `package.json` - I believe 99% users will already have a `package.json` and will be running `npm i` anyway because they either have a node project so they install dependencies or they use a different runtime that requires a plugin to properly bundle code (e.g. Python). So honestly I don't expect any annoyance because they're most likely running `npm i` anyway.

**Comment by mnapoli** [comment]
Discussion summary.

Scenarios:

1. no package.json | compose not installed at all
2. no package.json | they use yarn/something else
3. package.json but no `@serverless/compose` dependency
4. package.json with `@serverless/compose` dependency

In scenarios other than 4, let's trigger an error. In scenario 4 ideally let's install NPM dependencies automatically as this should have no negative side effect.

**Comment by pgrzesik** [comment]
Related PR: https://github.com/serverless/serverless/pull/10984
